# Generated by Django 4.1.4 on 2022-12-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address1',
            new_name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='items_json',
            field=models.CharField(default='', max_length=500),
        ),
    ]
