# Generated by Django 4.1.4 on 2022-12-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_address1_order_address_order_items_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('update_desc', models.CharField(default='', max_length=500)),
                ('timestap', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
