# Generated by Django 4.1.4 on 2022-12-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_orderupdate_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='timestap',
            new_name='timestamp',
        ),
    ]
